---
title: "VR Analysis"
author: "DB, JR"
date: "21 9 2021"
output: html_document
---


Load packages
```{r include=FALSE}
  library(Rmisc) 
  library(readxl)
  library(ggpubr) 
  library(rstatix) 
  library(WRS2)
  library(dplyr) 
  library(effectsize)
  library(dplyr)
  library(MOTE)
```

Load and prepare data
```{r}
long_d <- readRDS("long_d_0.rds")
long_d <- long_d %>% dplyr::select(id,gruppe,condition,t04_r0,t04_r1,t04_r2,t04_r3,t04_r4,t04_r5,t04_r6,t04_r7,t04_r8,t04_r9) %>% filter(condition == "Imagine") %>%
                    droplevels()

# Exclude participants due to technical errors or because they didnt not rate any stimuli as painful
long_d <- long_d %>% dplyr::filter(id != "VR_017") %>%
                               dplyr::filter(id != "VR_040") %>%
                               dplyr::filter(id != "VR_044") %>%
                               dplyr::filter(id != "VR_054") %>%
                               dplyr::filter(id != "VR_058") %>% 
                               dplyr::filter(id != "VR_010" & id != "VR_011" & id != "VR_014" & id != "VR_019" & id != "VR_024" & id != "VR_026" & id != "VR_029"& id != "VR_030"& id != "VR_031"& id != "VR_032"& id != "VR_033"& id != "VR_034"& id != "VR_038" ) 


aov_tsp <- long_d %>% dplyr::mutate(tsp = ((t04_r7 + t04_r8 + t04_r9)/3))


aov_oa <- aov_tsp %>% dplyr::select(id,gruppe,condition,t04_r0,t04_r1,t04_r2) %>% dplyr::mutate(tsp = (t04_r0 + t04_r1 + t04_r2)/3) %>%
                              dplyr::select(id,gruppe,condition,tsp)

aov_oa$condition <- car::recode(aov_oa$condition, "'Imagine' = 'Pre'")  
  
  
aov_bind <- dplyr::bind_rows(aov_tsp,aov_oa) %>% dplyr::select(id,gruppe,condition,tsp)
aov_tsp <- aov_bind 
aov_tsp$condition <- car::recode(aov_tsp$condition, "'Imagine' = 'Post'")  
```


Get descriptive statistics grouped by group and condition
("gruppe" = "group" in German)
```{r}
mean_tsp_gruppe<- aov_tsp %>%
  dplyr::group_by(gruppe) %>%
  dplyr::summarise(mean_tsp = mean(tsp),
            median_tsp = median(tsp),
            sd_tsp = sd(tsp),
            iqr_tsp = IQR(tsp),
            min_tsp = min(tsp),
            max_tsp = max(tsp)) %>% mutate(
            ci_test =  Rmisc::group.CI(tsp ~ gruppe, data = aov_tsp, ci = .95))

mean_tsp_condition <-  aov_tsp %>% dplyr::group_by(condition) %>%
    dplyr::summarise(mean_tsp = mean(tsp),
            median_tsp = median(tsp),
            sd_tsp = sd(tsp),
            iqr_tsp = IQR(tsp),
            min_tsp = min(tsp),
            max_tsp = max(tsp)) %>% mutate(
            ci_test =  Rmisc::group.CI(tsp ~ condition, data = aov_tsp, ci = .95))


ci_gc =  Rmisc::group.CI(tsp ~ condition * gruppe, data = aov_tsp, ci = .95)

mean_tsp_condition_gruppe <- aov_tsp %>% dplyr::group_by(gruppe, condition) %>%
    dplyr::summarise(mean_tsp = mean(tsp),
            median_tsp = median(tsp),
            sd_tsp = sd(tsp),
            iqr_tsp = IQR(tsp),
            min_tsp = min(tsp),
            max_tsp = max(tsp)) %>% dplyr::left_join(ci_gc, by = c("gruppe","condition"))
           
```

#Check assumptions for paired t-test
```{r}
bp_tsp <- ggpubr::ggboxplot(aov_tsp, x = "gruppe", y = "tsp", color = "condition", palette = "jco" , add = c("mean_se"))
bp_tsp


outliers_tsp <- aov_tsp %>%
  dplyr::group_by(gruppe, condition) %>%
  rstatix::identify_outliers(tsp)
outliers_tsp

shapiro_imagine <- aov_tsp %>%
  group_by(gruppe, condition) %>%
  shapiro_test(tsp)
shapiro_imagine



aov_dif <- long_d %>% dplyr::mutate(tsp1 = ((t04_r7 + t04_r8 + t04_r9)/3),
                             tsp2 = ((t04_r0 + t04_r1 + t04_r2)/3)) %>% dplyr::mutate(tsp_dif = tsp1-tsp2)
                         
nmv <- aov_dif %>% dplyr::select(id,gruppe,condition,tsp_dif)

shapiro <- nmv %>%
  dplyr::group_by(gruppe) %>%
  rstatix::shapiro_test(tsp_dif)
shapiro

out_pdt <- nmv %>%
  group_by(gruppe) %>%
  identify_outliers(tsp_dif)
out_pdt




# Three extreme outlieres (id09,id51,id55) two of them also regarding differences
# Differences not normal distributed 
# Only Cp-post data normal distributed

```



```{r}
aov_tsp %>% dplyr::group_by(gruppe) %>%
        rstatix::t_test(
         tsp ~ condition, paired = TRUE, 
         p.adjust.method = "none")

```



```{r}
aov_tsp %>% dplyr::group_by(gruppe) %>%
        rstatix::wilcox_test(
         tsp ~ condition, paired = TRUE, 
         p.adjust.method = "none")
# No differences
```

Get ES and CIs
```{r}
tresult <- aov_tsp %>% dplyr::group_by(gruppe)%>%
        rstatix::t_test(
         tsp ~ condition, paired = TRUE, 
         p.adjust.method = "none")

tresult <- as.data.frame(tresult)

tresult_hc <- tresult %>% dplyr::filter(gruppe == "HC")
tresult_cp <- tresult %>% dplyr::filter(gruppe == "CP")

d_hc <- as.data.frame(MOTE::d.dep.t.diff.t(tresult_hc[1,"statistic"], tresult_hc[1,"n1"], a = 0.05)) %>% dplyr::mutate(gruppe = "HC")
d_hc

d_cp <- as.data.frame(MOTE::d.dep.t.diff.t(tresult_cp[1,"statistic"], tresult_cp[1,"n1"], a = 0.05)) %>% dplyr::mutate(gruppe = "CP")
d_cp
```



Sensitivity Analysis
```{r}
aov_tsp_od <- aov_tsp %>% dplyr::filter(id != "VR_009" & id != "VR_051" & id != "VR_055")
aov_tsp_od %>% dplyr::group_by(gruppe) %>%
        rstatix::t_test(tsp ~ condition, paired = TRUE, 
         p.adjust.method = "none")
# no differences
```








