---
title: "CPM_pdt - Pre Analysis Imagine"
author: "JR"
date: "23.06.2023"
output: html_document
---


Load packages
```{r echo=TRUE, message=FALSE, warning=FALSE}
  library(Rmisc) 
  library(readxl)
  library(ggpubr) 
  library(rstatix) 
  library(WRS2)
  library(dplyr) 
  library(effectsize)
  library(dplyr)
  library(MOTE)
```

Load and prepare data
Excluding participants due to technical errors
```{r}
long_d <- readRDS("long_d_0.rds")

long_d <- long_d %>% select(id,gruppe,condition,t05_pdt0,t01_pdt0) %>% dplyr::filter(id != "VR_001") %>%
                                       dplyr::filter(id != "VR_010") %>%
                                       dplyr::filter(id != "VR_029") %>%
                                       dplyr::filter(id != "VR_048") 

aov_imagine_pdt <- long_d %>% dplyr::mutate(imagine_pdt = t05_pdt0) %>%
                                        dplyr::select(id,gruppe,condition,imagine_pdt,t01_pdt0)

aov_imagine_pdt <- aov_imagine_pdt %>% dplyr::filter(condition == "Imagine") %>% droplevels()


aov_oa <- aov_imagine_pdt %>% dplyr::select(id,gruppe,condition,t01_pdt0) %>% mutate(imagine_pdt = t01_pdt0) %>%
                              dplyr::select(id,gruppe,condition,imagine_pdt)

aov_oa$condition <- car::recode(aov_oa$condition, "'Imagine' = 'Dom'")  
  
  
aov_bind <- dplyr::bind_rows(aov_imagine_pdt,aov_oa) %>% select(id,gruppe,condition,imagine_pdt)

aov_imagine_pdt <- aov_bind
aov_imagine_pdt$condition <- car::recode(aov_imagine_pdt$condition, "'Imagine' = 'Cpm'")
aov_imagine_pdt
```


Get descriptive statistics grouped by group and condition
("gruppe" = "group" in German)
```{r}

mean_imagine_pdt_gruppe<- aov_imagine_pdt %>%
  dplyr::group_by(gruppe) %>%
  dplyr::summarise(mean_pdt = mean(imagine_pdt),
            median_imagine_pdt = median(imagine_pdt),
            sd_imagine_pdt = sd(imagine_pdt),
            iqr_imagine_pdt = IQR(imagine_pdt),
            min_imagine_pdt = min(imagine_pdt),
            max_imagine_pdt = max(imagine_pdt)) %>% mutate(
            ci_test =  Rmisc::group.CI(imagine_pdt ~ gruppe, data = aov_imagine_pdt, ci = .95))


mean_imagine_pdt_condition <-  aov_imagine_pdt %>% dplyr::group_by(condition) %>%
    dplyr::summarise(mean_pdt = mean(imagine_pdt),
            median_imagine_pdt = median(imagine_pdt),
            sd_imagine_pdt = sd(imagine_pdt),
            iqr_imagine_pdt = IQR(imagine_pdt),
            min_imagine_pdt = min(imagine_pdt),
            max_imagine_pdt = max(imagine_pdt)) %>% mutate(
            ci_test =  Rmisc::group.CI(imagine_pdt ~ condition, data = aov_imagine_pdt, ci = .95))


ci_gc =  Rmisc::group.CI(imagine_pdt ~ condition * gruppe, data = aov_imagine_pdt, ci = .95)

mean_imagine_pdt_condition_gruppe <- aov_imagine_pdt %>% dplyr::group_by(gruppe, condition) %>%
    dplyr::summarise(mean_pdt = mean(imagine_pdt),
            median_imagine_pdt = median(imagine_pdt),
            sd_imagine_pdt = sd(imagine_pdt),
            iqr_imagine_pdt = IQR(imagine_pdt),
            min_imagine_pdt = min(imagine_pdt),
            max_imagine_pdt = max(imagine_pdt)) %>% dplyr::left_join(ci_gc, by = c("gruppe","condition"))
```



#Check assumptions for paired t-test
```{r}
bp_imagine_pdt <- ggpubr::ggboxplot(aov_imagine_pdt, x = "gruppe", y = "imagine_pdt", color = "condition", palette = "jco" , add = c("mean_se"))
bp_imagine_pdt


outliers_imagine_pdt <- aov_imagine_pdt %>%
  dplyr::group_by(gruppe, condition) %>%
  rstatix::identify_outliers(imagine_pdt)
outliers_imagine_pdt

shapiro_imagine_pdt <- aov_imagine_pdt %>%
  group_by(gruppe, condition) %>%
  shapiro_test(imagine_pdt)
shapiro_imagine_pdt

nmv <- long_d %>% filter(condition == "Imagine") %>% dplyr::mutate(diff = t05_pdt0 - t01_pdt0) %>% dplyr::select(id,gruppe,condition,diff)

shapiro_pdt <- nmv %>%
  dplyr::group_by(gruppe) %>%
  rstatix::shapiro_test(diff)
shapiro_pdt

out_pdt <- nmv %>%
  dplyr::group_by(gruppe) %>%
  rstatix::identify_outliers(diff)
out_pdt


# No extreme outliers
# CP differences and data are not normal distributed
# One extreme outlier in CP regarding the differences 
```


```{r}
aov_imagine_pdt %>% dplyr::group_by(gruppe)%>%
        rstatix::t_test(
         imagine_pdt ~ condition, paired = TRUE,p.adjust.method = "none")
```

```{r}
aov_imagine_pdt %>% dplyr::filter(gruppe == "CP")%>%
        rstatix::wilcox_test(
         imagine_pdt ~ condition, paired = TRUE,p.adjust.method = "none")
# No differences
```

Get ES and CI
```{r}
tresult <- aov_imagine_pdt %>% dplyr::group_by(gruppe)%>%
        rstatix::t_test(imagine_pdt ~ condition, paired = TRUE, p.adjust.method = "none")

tresult <- as.data.frame(tresult)

tresult_hc <- tresult %>% dplyr::filter(gruppe == "HC")
tresult_cp <- tresult %>% dplyr::filter(gruppe == "CP")

d_hc <- as.data.frame(MOTE::d.dep.t.diff.t(tresult_hc[1,"statistic"], tresult_hc[1,"n1"], a = 0.05)) %>% mutate(gruppe = "HC")
d_hc

d_cp <- as.data.frame(MOTE::d.dep.t.diff.t(tresult_cp[1,"statistic"], tresult_cp[1,"n1"], a = 0.05)) %>% mutate(gruppe = "CP")
d_cp
```


Sensitivy Analysis
```{r}
aov_imagine_pdt %>% dplyr::filter(id != "VR_057") %>% dplyr::group_by(gruppe)%>%
        rstatix::t_test(
         imagine_pdt ~ condition, paired = TRUE,p.adjust.method = "none")
#No differences
```























